project:
  type: website
  resources:
    - calculator-live/

website:
  title: "Ketland Notes"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: notes.qmd
        text: Notes
      - href: research.qmd
        text: Research
      - href: blogposts.qmd
        text: Blogposts
      - href: calculator.qmd
        text: Calculator

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

filters:
  - shinylive

editor: source