---
title: "Publications"
format: html
---

**Book**

- *The Application of Mathematics: Entanglement and Instantiation*. Cambridge University Press, 2026. [CUP page here](https://www.cambridge.org/core/books/application-of-mathematics/A3F0C474FEDC91BFAF90741AB3AEB3ED). 

  Description: Why is abstract mathematics applicable within science? Jeffrey Ketland describes the metatheory of the application of mathematics in science and highlights the 'entanglement' of physical systems with mathematical objects and structures. Applied mathematics inferences are regimented into '**canonical form**', 
  
  $$\overbrace{ \, \, \textsf{AM} \, \, }^{ \text{ambient base} } + \overbrace{ \, \, \Sigma  \, \, }^{ \text{scientific premises} } \vdash \overbrace{ \, \, \varphi \, \, }^{ \text{scientific conclusion}  }$$
  
  involving an ambient foundational base theory $\textsf{AM}$ and the specific physical premises $\Sigma$ and conclusions $\varphi$. These latter are formulated using concepts called 'entanglers'---that is `mixed' predicates and function symbols---which relate physical objects and systems to mathematical objects. The simplest example is the membership predicate, 
  
  $$x \in y$$
  
  Other examples are 
 
  - coordinate functions $\Phi(p) = \{x^{\mu} \}$, 
  - quantity functions $Q(a) = x$ (such as mass, length, or temporal duration), 
  - and fields (on space or spacetime), $\psi(p) = v$. 
 
  Mathematical terms denoting these, as well as impure sets, relations, and structures, are called '**entanglement constants**'. Ketland shows that such inferences satisfy a form of topic neutrality called Hilbert's Beermug Principle, 
  
  $$\textsf{AM} \vdash \Sigma(P_1, \dots) \to \varphi(P_1, \dots) \text{ iff } \textsf{AM} \vdash \forall X_1, \dots [\Sigma(X_1, \dots) \to \varphi(X_1, \dots)].$$
  
  Then all such inferences---i.e., deriving a scientific conclusion $\varphi(P_1, \dots)$ from scientific premises $\Sigma(P_1, \dots)$, using mathematics---can be seen to be **instantiations** of general mathematical theorems with such constants.

**Published articles**

**Refereed Articles**

- 2023: **Axiomatization of Galilean Spacetime.** *Dialectica*, 77 (2): 153–202.

  Description: Provides a second-order synthetic axiomatization $\mathsf{Gal}(1,3)$ for Galilean spacetime—the background spacetime of Newtonian classical mechanics—using primitive notions of betweenness $\textsf{B}(p,q,r$), simultaneity $p \sim q$, and hypersurface congruence $p q \equiv^{\sim} r s$. Along with the axioms $\textsf{Comprehension}$ and $\textsf{Extensionality}$ for $\textsf{MSOL}$ we have:
  
  - $\textsf{BG}(4)$ (i.e., ordered affine geometry, or betweenness geometry, in four dimensions).
  
  - $[\textsf{EG}(3)]^{\sim}$ (i.e., Euclidean geometry in three dimensions, relativized to simultaneity hypersurfaces).
  
  - $\sim$ is an equivalence relation.

  - $p q \equiv^{\sim} r s \to (p \sim q \wedge p \sim r \wedge p \sim s)$.
  
  - $\textsf{pgram}(p,q,p',q') \wedge \textsf{pgram}(r,s,r',s') \wedge pp' \parallel rr' \to \, (pq \equiv^{\sim} rs \to p' q' \equiv^{\sim} r's')$.
  
  These axioms are categorical and determine Galilean spacetime up to isomorphism.

- 2022b: **Standard Formalization.** *Global Philosophy*, 32 (Suppl 3): 711–748.

  Description: Shows how to construct standard first-order formalizations of mathematicized scientific theories, involving differential equations and scalar fields, working with a base theory $\textsf{ZFCA}_{\sigma}$ of set theory with atoms/urelements, where $\sigma$ is an adjustible signature for applications.

- 2022a: **Boolos's Curious Inference in Isabelle/HOL.** Archive of Formal Proofs (July 2022).

  Description: Formalizes George Boolos's demonstration of the computational and deductive speed-up of higher-order logic over first-order logic, verifying fourteen constituent lemmas using Isabelle/HOL.

- 2021b: **Foundations of Applied Mathematics I**. *Synthese* **199**: 4151--4193.

- 2021a: **Computation and Indispensability**. *Logic and Logical Philosophy* **30** (1): 61--78.

- 2020b: **Bases for Structures and Theories II**. *Logica Universalis* **14** (4): 461--479.

- 2020a: **Bases for Structures and Theories I**. *Logica Universalis* **14** (3): 357--381.

- 2016: **Arithmetic with Fusions** (with T. Schindler). *Logique et Analyse* **234**: 207--226.

  Description: We show that the result of adding the mereological theory of fusions to first-order Peano Arithmetic $\textsf{PA}$ yields a theory which interprets second-order Peano Arithmetic $\textsf{PA}_2$.

- 2013: **There’s Glory for You!** *Philosophy* **89**: 3--29.

- 2012: **Validity as a Primitive**. *Analysis* **72**: 421--430.

- 2011b: **Nominalistic Adequacy**. *Proceedings of the Aristotelian Society* **111**: 201--217.

- 2011a: **Identity and Indiscernibility**. *The Review of Symbolic Logic* **4**: 171--185.

- 2009a. **Empirical Adequacy and Ramsification, II**. In A. Heike & H. Leitgeb (eds.) 2009. *Reduction--Abstraction--Analysis*, Proceedings of 31st International Wittgenstein Symposium (Kirchberg, Austria). Ontos Press.

- 2007: **A Comment on Bermúdez Concerning the Definability of Identity**. *Analysis* **67**: 315--318.

- 2006: **Structuralism and the Identity of Indiscernibles**. *Analysis* **66**: 303--315.

- 2005c. **Yablo’s Paradox and** $\omega$-**Inconsistency**. *Synthese* **145**: 295--307.

  Description: I discuss the formalization of Yablo's Paradox in the context of arithmetic. A unary "truth predicate" $\textsf{T}$ is added to $L_{\textsf{PA}}$ along with certain axioms. Using (uniform) Diagonalization, one can define a formula $Y(x)$ and prove in $\textsf{PA}$ (in the extended language):
  
  $$\forall x \, [Y(x) \leftrightarrow (\forall y > x) \, \neg \textsf{T}(\ulcorner Y(\dot{y}))]$$
  A Yablo sentence is formed by substituting (the numeral for) $n$ for $x$. I.e., the $n$th Yablo sentence is $Y(n)$. I then study what happens when one adds certain truth axioms to this theory.

- 2005b: **Jacquette on Grelling’s Paradox**. *Analysis* **65**: 258--260.

- 2005a. **Some More Curious Inferences**. *Analysis* **65**: 18--24.

- 2004b: **Bueno and Colyvan on Yablo’s Paradox**. *Analysis* **64**: 165--172.

  Description: Buenos and Colyvan argue that Yablo's Paradox can be reproduced using simply the usual *local* disquotation scheme:
  
  $$\textsf{T}(\ulcorner \varphi \urcorner) \leftrightarrow \varphi$$
  I.e., the set of biconditionals:
  
  $$\textsf{T}(\ulcorner Y(n) \urcorner) \leftrightarrow Y(n)$$
  
  I argue that this only yields on $\omega$-inconsistency. To get a genuine contradition, one must include the *uniform* disquotation scheme:
  $$\forall x \, [\textsf{T}(\ulcorner \varphi(\dot{x}) \urcorner) \leftrightarrow \varphi(x)]$$
  
  I.e., the single quantified formula:
  
  $$\forall x \, [\textsf{T}(\ulcorner Y(\dot{x}) \urcorner) \leftrightarrow Y(x)]$$

- 2004a: **Empirical Adequacy and Ramsification**. *BJPS* **55**: 287--300.

  Description: The structural realist (see Worrall 1989) aims to interpolate between instrumentalism and scientific realism, by identifying some sort of "middle-ground". The suggestion made by Worrall and others is that the *Ramsey sentence* $\textsf{Ram}(T)$ of a theory $T$ does this job. I argue that it does not. Roughly speaking, $\textsf{Ram}(T)$ is true if and only if $T$ is empirically adequate. (The details are a bit more complicated, and involve the cardinality of models.) This means that structural realism is, more or less, equivalent to *instrumentalism*.

- 2003b: **On Wright’s Inductive Definition of Coherence Truth for Arithmetic**. *Analysis* **63**: 6--15.

- 2003a: **Can a Many-Valued Language Functionally Represent its Own Semantics?**. *Analysis* **63**: 292--297.

- 2002b: **Hume = Small Hume**. *Analysis* **62**: 92--93.

- 2002a: **A Proof of the (Strengthened) Liar Formula in a Semantical Extension of Peano Arithmetic**. *Analysis* **60**: 1--4.

- 1999: **Deflationism and Tarski’s Paradise**. *Mind* **108**: 69--94.

**Refereed Replies**

- 2010: **Truth, Conservativeness and Provability -- Reply to Cieśliński**. *Mind* **120**: 423--436.

- 2009b: **Deflationism and Beth’s Theorem -- Reply to Bays**. *Mind* **118**: 1075--1079.

- 2005d: **Deflationism and the Gödel Phenomena -- Reply to Tennant**. *Mind* **114**: 75--88.

**Invited & Encyclopaedia Articles**

- 2009b: **Truth**, in John Shand (ed.) *The Central Issues in Philosophy*. Blackwell, 2009.

- 2005f: **Craig’s Theorem**, in D. Borchert (ed.), *Macmillan Encyclopedia of Philosophy*.

- 2005e: **Second-Order Logic**, in D. Borchert (ed.), *Macmillan Encyclopedia of Philosophy*.

**Reviews**

- 2020c: **Review: C. Cieśliński, *The Lightness of Truth* (OUP, 2017)**. *Studia Logica* **108** (1): 159--162.

- 2005g: **Review: P. Horwich, *From a Deflationary Point of View* (OUP, 2004)**. *Notre Dame Philosophical Reviews*.

- 2001: **Review: S.G. Simpson (1999), *Subsystems of Second-Order Arithmetic* (Springer/ASL, 1998)**. *BJPS* **52**: 191--195.

- 2000: **Review: G. Stokes, *Popper: Philosophy, Politics and Scientific Method* (Polity, 1998)**. *BJPS* **51**: 363--369.

**Unpublished articles**

- 2023: **Definitional Equivalence of $\textsf{Gal}(1,3)$ and $\textsf{Gal}_F(1,3)$**.

  Description: Shows how to formulate two second-order theories axiomatizing Galilean spacetime, with slightly different primitives. $\textsf{Gal}_F(1,3)$ is given in Field, 1980, *Science Without Numbers*; $\textsf{Gal}(1,3)$ is given in "Axiomatization of Galilean Spacetime", *Dialectica*, 77), and proves that these theories are definitionally equivalent.

- 2023: **Length Abstraction in Euclidean Geometry.**.

  Description: Defines abstract lengths in Euclidean geometry via an abstraction axiom, characterizing the length structure and its symmetry group alongside coordinate relationships.

- 2022: **Empirical Adequacy and Effect Completeness**.