---
title: "CV - Jeffrey Ketland"
format: html
---

This is my CV. A more detailed PDF version can be found  [here](/CV/CV_2026.pdf).

**Personal Details**

* Born: 20 March 1964, Birmingham, England.

* Residence: Liberton, Edinburgh, Scotland.

* Email: jeffreyketland@gmail.com

* Twitter: @jeffreyketland

**Education**

* **1975 -- 1982:** King Edwards Camp Hill School for Boys, Birmingham.

* **1982 -- 1985:** Trinity College, Cambridge. BA Theoretical Physics.

* **1985 -- 1986:** Trinity College, Cambridge. Part III Maths Tripos.

* **1990 -- 1992:** University of Warwick. MA Philosophy.

* **1994 -- 1998:** London School of Economics & Political Science. PhD Philosophy of Science.


**Work**

* **1991 -- 1991:** Teaching Assistant, University of Warwick.

* **1996 -- 1998:** Temporary Lecturer, Richmond College.

* **1996 -- 1998:** Teaching Assistant, LSE.

* **1998 -- 1999:** Temporary Lecturer, LSE.

* **2000 -- 2001:** Lecturer, University of Nottingham.

* **2001 -- 2002:** Post-doctoral Fellow, King's College London.

* **2002 -- 2003:** Temporary Lecturer, University of Leeds.

* **2003 -- 2004:** Temporary Lecturer, University of Cambridge.

* **2004 -- 2011:** Lecturer, University of Edinburgh.

* **2011 -- 2012:** Lecturer, University of Munich.

* **2012 -- 2016:** Associate Professor & Fellow, University of Oxford, Pembroke College.

* **2019 -- 2025:** Research Professor, University of Warsaw.

* **2025 -- present:** Retired.