---
title: "The Superior Virtue of the Oppressed (Russell, 1937)"
date: "2018-04-11"
categories: [Politics, Social Philosophy]
---


[This essay was published by Bertrand Russell in 1937 in *The Nation*, 144. It was republished in Russell’s *Unpopular Essays* (1950).]

"The Superior Virtue of the Oppressed", by Bertrand Russell, 1937

ONE of the persistent delusions of mankind is that some sections of the human race are morally better or worse than others. This belief has many different forms, none of which has any rational basis. It is natural to think well of ourselves, and thence, if our mental processes are simple, of our sex, our class, our nation, and our age. But among writers, especially moralists, a less direct expression of self-esteem is common. They tend to think ill of their neighbors and acquaintances, and therefore to think well of the Sections of mankind to which they themselves do not belong. Lao-tse admired the “pure men of old,” who lived before the advent of Confucian sophistication. Tacitus and Madame de Stael admired the Germans because they had no emperor. Locke thought well of the “intelligent American” because he was not led astray by Cartesian sophistries.

A rather curious form of this admiration for groups to which the admirer does not belong is the belief in the superior virtue of the oppressed: subject nations, the poor, women, and children. The eighteenth century, while conquering America from the Indians, reducing the peasantry to the condition of pauper laborers, and introducing the cruelties of early industrialism, loved to sentimentalize about the “noble savage” and the “simple annals of the poor.” Virtue, it was said, was not to be found in courts: but court ladies could almost secure it by masquerading as shepherdesses. And as for the male sex:

> Happy the man whose wish and care
> A lew paternal acres bound.

Nevertheless, for himself Pope preferred London and his villa at Twickenham.

At the French Revolution the superior virtue of the poor became a party question, and has remained so ever since. To reactionaries they became the “rabble” or the “mob.” The rich discovered, with surprise, that some people were so poor as not to own even “a few paternal acres.” Liberals, however, still continued to idealize the rural poor, while intellectual Socialists and Communists did the same for the urban proletariat – a fashion to which, since it only became important in the twentieth century, I shall return later.

Nationalism introduced, in the nineteenth century, a substitute for the noble savage the patriot of an oppressed nation. The Greeks until they had achieved liberation from the Turks, the Hungarians until the Ausgleich of 1867, the Italians until 1870, and the Poles until after the 1914-18 war were regarded romantically as gifted poetic races, too idealistic to succeed in this wicked world. The Irish were regarded by the English as possessed of a special charm and mystical insight until 1921, when it was found that the expense of continuing to oppress them would be prohibitive. One by one these various nations rose to independence, and were found to be just like everybody else; but the experience of those already liberated did nothing to destroy the illusion as regards those who were still struggling. English old ladies still sentimentalize about the “wisdom of the East” and American intellectuals about the “earth consciousness” of the Negro.

Women, being the objects of the strongest emotions, have been viewed even more irrationally than the poor or the subject nations. I am thinking not of what poets have to say but of the sober opinions of men who imagine themselves rational. The church had two opposite attitudes: on the one hand, woman was the Temptress, who led monks and others into sin; on the other hand, she was capable of saintliness to an almost greater degree than man. Theologically, the two types were represented by Eve and the Virgin. In the nineteenth century the temptress fell into the background; there were, of course, “bad” women, but Victorian worthies, unlike St. Augustine and his successors, would not admit that such sinners could tempt them, and did not like to acknowledge their existence. A kind of combination of the Madonna and the lady of chivalry was created as the ideal of the ordinary married woman. She was delicate and dainty, she had a bloom which would be rubbed off by contact with the rough world, she had ideals which might be dimmed by contact with wickedness; like the Celts and the Slavs and the noble savage, but to an even greater degree, she enjoyed a spiritual nature, which made her the superior of man but unfitted her for business or politics or the control of her own fortune. This point of view is still not entirely extinct. Not long ago, in reply to a speech I had made in favor of equal pay for equal work, an English schoolmaster sent me a pamphlet published by a schoolmasters’ association, setting forth the opposite opinion, which it supports with curious arguments. It says of woman: “We gladly place her first as a spiritual force; we acknowledge and reverence her as the ‘angelic part of humanity’; we give her superiority in all the graces and refinements we are capable of as human beings; we wish her to retain all her winsome womanly ways.” “This appeal” that women should be content with lower rates of pay “goes forth from us to them,” so we are assured, “in no selfish spirit, but out of respect and devotion to our mothers, wives, sisters, and daughters. . . . Our purpose is a sacred one, a real spiritual crusade.

Fifty or sixty years ago such language would have roused no comment except on the part of a handful of feminists; now, since women have acquired the vote, it has come to seem an anachronism. The belief in their “spiritual” superiority was part and parcel of the determination to keep them inferior economically and politically. When men were worsted in this battle, they had to respect women, and therefore gave up offering them “reverence” as a consolation for inferiority.

A somewhat similar development has taken place in the adult view of children. Children, like women, were theologically wicked, especially among evangelicals. They were limbs of Satan, they were unregenerate; as Dr. Watts so admirably put it:

> One stroke of His almighty rod
> Can send young sinners quick to Hell.

It was necessary that they should be “saved.” At Wesley’s school “a general conversion was once effected, . . one poor boy only excepted, who unfortunately resisted the influence of the Holy Spirit, for which he was severely flogged. . . .” But during the nineteenth century, when parental authority, like that of kings and priests and husbands, felt itself threatened, subtler methods of quelling insubordination came into vogue. Children were “innocent”; like good women they had a “bloom”; they must be protected from knowledge of evil lest their bloom should be lost. Moreover, they had a special kind of wisdom. Wordsworth made this view popular among English-speaking people. He first made it fashionable to credit children with

> High instincts before which our mortal nature
> Did tremble like a guilty thing surprised.

No one in the eighteenth century would have said to his little daughter, unless she were dead:


> Thou liest in Abraham’s bosom all the year
> And worships’t at the temple’s inner shrine.

But in the nineteenth century this view became quite common; and respectable members of the Episcopal church or even of the Catholic church shamelessly ignored Original Sin to dally with the fashionable heresy that

> . . . trailing clouds of glory do we cone
>
> From God who is our home:
> Heaven lies about us in our infancy.

This led to the usual development. It began to seem hardly right to spank a creature that was lying in Abraham’s bosom, or to use the rod rather than a high instincts “to make it “tremble like a guilty thing surprised/’ And so parents and schoolmasters found that the pleasures they had derived from inflicting chastisement were being curtailed and a theory of education grew up which made it necessary to consider the child’s welfare, and not only the adult’s convenience and sense of power. The only consolation the adults could allow themselves was the invention of a new child psychology. Children, after being limbs of Satan in traditional theology and mystically illuminated angels in the minds of educational reformers, have reverted to being little devils not theological demons inspired by the Evil One, but scientific Freudian abominations inspired by the Unconscious. They are, it must be said, far more wicked than they were in the diatribes of the monks; they display, in modern textbooks, an ingenuity and persistence in sinful imaginings to which in the past there was nothing comparable except St. Anthony. Is all this the objective truth at last? Or is it merely an adult imaginative compensation for being no longer allowed to wallop the little pests? Let the Freudians answer, each for the others.

As appears from the various instances that we have considered, the stage in which superior virtue Is attributed to the oppressed is transient and unstable. It begins only when the oppressors come to have a bad conscience, and this only happens when their power is no longer secure. The idealizing of the victim is useful for a time: if virtue is the greatest of goods, and if subjection makes people virtuous, it is kind to refuse them power, since it would destroy their virtue. If it is difficult for a rich man to enter the kingdom of heaven, it is a noble act on his part to keep his wealth and so imperil his eternal bliss for the benefit of his poorer brethren. It was a fine self-sacrifice on the part of men to relieve women of the dirty work of politics. And so on. But sooner or later the oppressed class will argue that its superior virtue is a reason in favor of its having power, and the oppressors will find their own weapons turned against them. When at last power has been equalized, it becomes apparent to everybody that all the talk about superior virtue was nonsense, and that it was quite unnecessary as a basis for the claim to equality.

In regard to the Italians, the Hungarians, women, and children, we have ran through the whole cycle. But we are still in the middle of it in the case which is of the most importance at the present time namely, that of the proletariat. Admiration of the proletariat is very modern. The eighteenth century, when it praised “the poor,” thought always of the rural poor. Jefferson’s democracy stopped short at the urban mob; he wished America to remain a country of agriculturists. Admiration of the proletariat, like that of dams, power stations, and airplanes, is part of the ideology of the machine age. Considered in human terms, it has as little in its favor as belief in Celtic magic, the Slav soul, women’s intuition, and children’s innocence. If it were indeed the case that bad nourishment, little education, lack of air and sunshine, unhealthy housing conditions, and overwork produce better people than are produced by good nourishment, open air, adequate education and housing, and a reasonable amount of leisure, the whole case for economic reconstruction would collapse, and we could rejoice that such a large percentage of the population enjoys the conditions that make for virtue. But obvious as this argument is, many Socialist and Communist intellectuals consider it de rigueur to pretend to find the proletariat more amiable than other people, while professing a desire to abolish the conditions which, according to them, alone produce good human beings. Children were idealized by Wordsworth and un-idealized by Freud. Marx was the Wordsworth of the proletariat; its Freud is still to come.

